spring:
  mail:
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtps
    test-connection: false
  data:
    mongodb:
      uri: ${mongodb.enableFalse}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  datasource:
    username: ${mysql.username}
    password: ${mysql.password}
    url: jdbc:mysql://${mysql.url}:${mysql.port}/${mysql.database}?useSSL=false&serverTimezone=GMT%2B8&character=UTF8
    hikari:
      auto-commit: true
      connection-timeout: 60000
      initialization-fail-timeout: 60000
      minimum-idle: 10
      max-lifetime: 300000
      maximum-pool-size: 100
      idle-timeout: 150000
  boot:
    admin:
      client:
        url: http://${admin.url}:${admin.port}
        instance:
          name: Permission Manager System
          prefer-ip: true
        username: ${admin.username}
        password: ${admin.password}
  redis:
    host: ${redis.host}
    port: ${redis.port}
server:
  tomcat:
    accept-count: 50
management:
  endpoint:
    logfile:
      external-file: ${spring.log.external-file}
  endpoints:
    web:
      exposure:
        include: "*"