version: '3'
services:
  storage:
    image: registry.cn-hangzhou.aliyuncs.com/maihx/fastdfs
    container_name: storage
    network_mode: host
    command: sh storage.sh
    restart: always
    privileged: true
    environment:
      TRACKER_IP: 39.105.148.214:22122
      GROUP_NAME: group1
      SERVER_PORT: 8899
